// <auto-generated />
namespace ECommerceApp.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class LatestChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LatestChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "202001121215470_LatestChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
